dist: xenial

addons:
  apt:
    packages:
      - ant-optional

language: php

php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.4snapshot"
  - "nightly"

env:
  - CONTAO_VERSION=contao/core-bundle ~4.4.0
  - CONTAO_VERSION=contao/core-bundle ~4.5.0
  - CONTAO_VERSION=contao/core-bundle ~4.6.0

matrix:
  exclude:
  allow_failures:
    - php: "nightly"
    - php: "7.4snapshot"

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer require $CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

git:
  depth: 2147483647

cache:
  directories:
    - vendor
